### ISSUE TITLE
Deleting Date, DateTime, and Identity types from a Collection does not remove the selected item

### ISSUE THREAD

**Issue by jdville03** [openlawteam/openlaw-elements#41]
With a Collection of `Date`, `DateTime`~, or `Identity`~ variables, the last item from the list will be the one to be removed even when you try to delete one before that.

https://www.useloom.com/share/5f33ab86059643759fa5fdce180a80a5

**Comment by jtrein** [comment]
#45 fixes Identity

**Comment by jtrein** [comment]
Dates are a bit harder to fix. I may go back in and do my best to add the cleanest hack I can. I opened a bug in core: https://github.com/openlawteam/openlaw-core/issues/97

**Comment by jeamick** [comment]
Hello @jtrein,

Is there a way you could explain why Dates are harder to fix ?
Thanks

JM

**Comment by jtrein** [comment]
Hi @jeamick, from what I have understood it's a bug in our openlaw-core library (https://github.com/openlawteam/openlaw-core/issues/97). The dates appear to change within a Collection (maybe also outside a Collection) as the values within the Collection are updated. More information about the bug with Dates will be handled via https://github.com/openlawteam/openlaw-core/issues/97.

I'll bump the issue over there to see if any planned work to investigate is ahead.

**Comment by jtrein** [comment]
A fix should be merged soon. https://github.com/openlawteam/openlaw-core/pull/175

**Comment by jtrein** [comment]
Fixed
