### ISSUE TITLE
Fix how checkValidity is handled

### ISSUE THREAD

**Issue by jtrein** [openlawteam/openlaw-elements#65]
Related to https://github.com/openlawteam/openlaw-client/pull/82

Need to change each component's handling of `this.props.getValidity` to introduce the fix in the `openlaw-client` PR above.

**Comment by jdville03** [comment]
`openlaw@0.2.13` was released and includes the fix in openlawteam/openlaw-client#82. The bump in `openlaw-app` for that is pending in openlawteam/openlaw-app#2591.

**Comment by jtrein** [comment]
Handled in PR #67
